id: P000746
initial_creation_type: ocr
source_metadata:
  id: bdr:W21707
  title: གཏམ་པདྨ་འི་ཚལ་གྱི་ཟློས་གར།
  author: ''
  volumes:
    59ec0214a8384d458f5a29215a611801:
      image_group_id: I1KG22775
      title: ''
      volume_number: 1
      total_pages: 166
