id: P000746
initial_creation_type: ocr
created_at: 31/03/2020
last_modified_at: 24/11/2021
source_metadata:
  id: bdr:W21707
  title: གཏམ་པདྨ་འི་ཚལ་གྱི་ཟློས་གར།
  author: ''
  volumes:
    59ec0214a8384d458f5a29215a611801:
      image_group_id: I1KG22775
      title: ''
      volume_number: 1
      total_pages: 166
      base_file: v001.txt
